package com.zlzkj.app.model;

import java.io.Serializable;

public class AccessControlKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesscontrol.userid
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesscontrol.recordtypeid
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    private String recordtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesscontrol.userid
     *
     * @return the value of accesscontrol.userid
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesscontrol.userid
     *
     * @param userid the value for accesscontrol.userid
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesscontrol.recordtypeid
     *
     * @return the value of accesscontrol.recordtypeid
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    public String getRecordtypeid() {
        return recordtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesscontrol.recordtypeid
     *
     * @param recordtypeid the value for accesscontrol.recordtypeid
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    public void setRecordtypeid(String recordtypeid) {
        this.recordtypeid = recordtypeid;
    }
}