package com.zlzkj.app.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Role implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleId
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.code
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.description
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.reserved1
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.reserved2
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    private String reserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.reservedi1
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    private Long reservedi1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.reservedi2
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    private Long reservedi2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.reservedd1
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    private BigDecimal reservedd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.reservedd2
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    private BigDecimal reservedd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.code
     *
     * @return the value of role.code
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.code
     *
     * @param code the value for role.code
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.description
     *
     * @return the value of role.description
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.description
     *
     * @param description the value for role.description
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.reserved1
     *
     * @return the value of role.reserved1
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.reserved1
     *
     * @param reserved1 the value for role.reserved1
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.reserved2
     *
     * @return the value of role.reserved2
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.reserved2
     *
     * @param reserved2 the value for role.reserved2
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.reservedi1
     *
     * @return the value of role.reservedi1
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public Long getReservedi1() {
        return reservedi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.reservedi1
     *
     * @param reservedi1 the value for role.reservedi1
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public void setReservedi1(Long reservedi1) {
        this.reservedi1 = reservedi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.reservedi2
     *
     * @return the value of role.reservedi2
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public Long getReservedi2() {
        return reservedi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.reservedi2
     *
     * @param reservedi2 the value for role.reservedi2
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public void setReservedi2(Long reservedi2) {
        this.reservedi2 = reservedi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.reservedd1
     *
     * @return the value of role.reservedd1
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public BigDecimal getReservedd1() {
        return reservedd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.reservedd1
     *
     * @param reservedd1 the value for role.reservedd1
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public void setReservedd1(BigDecimal reservedd1) {
        this.reservedd1 = reservedd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.reservedd2
     *
     * @return the value of role.reservedd2
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public BigDecimal getReservedd2() {
        return reservedd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.reservedd2
     *
     * @param reservedd2 the value for role.reservedd2
     *
     * @mbggenerated Fri Jul 29 11:01:18 CST 2016
     */
    public void setReservedd2(BigDecimal reservedd2) {
        this.reservedd2 = reservedd2;
    }
}